Create database MESA_TRABAJO;

use MESA_TRABAJO;

CREATE TABLE ROL(
    ROL_ID INT AUTO_INCREMENT NOT NULL,
    ROL_DESCRIPCION VARCHAR(45) NOT NULL,
    PRIMARY KEY (ROL_ID)
);

CREATE TABLE USUARIO (
    USU_ID INT AUTO_INCREMENT NOT NULL,
    USU_MAIL VARCHAR(45) NOT NULL,
    USU_PASSWORD VARCHAR(80) NOT NULL,
    USU_ROL INT NOT NULL,
    PRIMARY KEY (USU_ID),
    FOREIGN KEY (USU_ROL) REFERENCES ROL(ROL_ID)
);


CREATE TABLE TIPO(
    TIP_ID INT AUTO_INCREMENT NOT NULL,
    TIP_DESCRIPCION VARCHAR(45) NOT NULL,
    PRIMARY KEY (TIP_ID)
);

CREATE TABLE ESTADO(
    EST_ID INT AUTO_INCREMENT NOT NULL,
    EST_DESCRIPCION VARCHAR(45) NOT NULL,
    PRIMARY KEY (EST_ID)
);

create TABLE CASO(
    CAS_ID INT AUTO_INCREMENT NOT NULL,
    CAS_TIPO INT NOT NULL,
    CAS_ESTADO INT NOT NULL,
    CAS_FECHA_INI VARCHAR(45) NOT NULL,
    CAS_FECHA_CIERRE VARCHAR(45) NOT NULL,
    CAS_USUARIO INT NOT NULL,
    PRIMARY KEY (CAS_ID),
    FOREIGN KEY (CAS_USUARIO) REFERENCES USUARIO(USU_ID),
    FOREIGN KEY (CAS_TIPO) REFERENCES TIPO(TIP_ID),
    FOREIGN KEY (CAS_ESTADO) REFERENCES ESTADO(EST_ID)
);

CREATE TABLE DESCRIPCION (
    DES_ID INT AUTO_INCREMENT NOT NULL,
    DES_DESCRIPCION varchar(90),
    DES_CASO INT NOT NULL,
    PRIMARY KEY (DES_ID),
    FOREIGN KEY (DES_CASO) REFERENCES CASO(CAS_ID)
);

CREATE TABLE SOLUCION (
    SOL_ID INT AUTO_INCREMENT NOT NULL,
    SOL_DESCRIPCION VARCHAR(200) NOT NULL,
    SOL_FECHA VARCHAR(45) NOT NULL,
    SOL_USUARIO INT NOT NULL,          
    SOL_CASO INT NOT NULL,
    PRIMARY KEY (SOL_ID),
    FOREIGN KEY (SOL_CASO) REFERENCES CASO(CAS_ID),
    FOREIGN KEY (SOL_USUARIO) REFERENCES USUARIO(USU_ID)
) ;

insert into Rol values ('1','Administrador');
insert into Rol values ('2','Trabajador');
insert into Rol values ('3','Usuario');

insert into Usuario values ('','asdf@gmail.com','$2y$10$zlpaz0O4OoETL334F0tc0OoHRHxXwvHKZH9rAWlMaQmGDVhen8m/e','1')
